export const PROPERTIES = [
    { id: 1, title: 'The Azure Penthouse', location: 'Chelsea, New York, 10001', price: 8500, beds: 3, baths: 2.5, sqft: 2240, tags: ['VERIFIED LANDLORD', 'AVAILABLE NOW'], image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', petFriendly: true },
    { id: 2, title: 'Harbor Point Suites', location: 'Brooklyn, NY 11201', price: 4200, beds: 1, baths: 1, sqft: 850, tags: ['NO PARKING'], image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', petFriendly: false },
    { id: 3, title: 'The Glass House Condo', location: 'Midtown, NY 10019', price: 5800, beds: 2, baths: 2, sqft: 1100, tags: ['PRICE CUT'], image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', petFriendly: true },
    { id: 4, title: 'Riverside Loft', location: 'Jersey City, NJ 07302', price: 3900, beds: 1, baths: 1, sqft: 900, tags: ['NEW LISTING'], image: 'https://images.unsplash.com/photo-1556912172-45b7ee8819d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', petFriendly: true },
    { id: 5, title: 'Village Studio', location: 'West Village, NY 10014', price: 2750, beds: 0, baths: 1, sqft: 450, tags: ['LOW AVAILABILITY'], image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', petFriendly: false },
  ];
  
  export const ANALYSIS_FLAGS = [
    { id: 1, type: 'red', title: 'Excessive Security Deposit', text: 'The lease requires a 2-month security deposit. California Civil Code 1950.5 limits security deposits to 2 months for unfurnished units, but this is at the maximum allowed — verify if the unit is furnished.', action: 'Confirm unit is unfurnished; if furnished, negotiate down to 2 months max.', section: 'Section 3.1', tag: 'DEPOSIT' },
    { id: 2, type: 'red', title: 'Insufficient Entry Notice', text: 'The landlord can enter with only 12-hour notice. California Civil Code 1954 requires a minimum of 24 hours written notice before entry.', action: 'Demand 24-hour written notice per CA Civil Code 1954.', section: 'Section 7.2', tag: 'ENTRY NOTICE' },
    { id: 3, type: 'red', title: 'Excessive Rent Increase Cap', text: 'Rent increases of up to 10% annually exceed the limit set by California AB 1482 (Tenant Protection Act), which caps annual increases at 5% + CPI or 10%, whichever is lower.', action: 'Negotiate rent increase cap to 5% + CPI per AB 1482.', section: 'Section 2.3', tag: 'RENT INCREASE' },
    { id: 4, type: 'red', title: 'Tenant Repair Responsibility', text: 'Tenant is responsible for all repairs under $200. This may conflict with California habitability laws requiring landlords to maintain habitable conditions (Green v. Superior Court).', action: 'Strike clause or limit to cosmetic/non-essential repairs only.', section: 'Section 9.1', tag: 'REPAIRS' },
    { id: 5, type: 'red', title: 'Auto-Renewal Trap', text: 'The lease auto-renews for 12 months if not cancelled 90 days before expiry. The 90-day cancellation window combined with a full 12-month renewal is unusually restrictive.', action: 'Negotiate 30-day cancellation window or month-to-month renewal.', section: 'Section 11.4', tag: 'RENEWAL' },
    { id: 6, type: 'green', title: 'Standard Monthly Rent', text: '$1,800/month rent is within the typical market range for California rental properties of this type. No hidden fees or variable charges detected.', action: 'At market rate for the area.', section: 'Section 1.1', tag: 'RENT' },
    { id: 7, type: 'green', title: 'Defined Early Termination Fee', text: 'The $500 early termination fee is clearly stated and reasonable compared to market standards, which often charge 2 months rent or more.', action: 'Below-market termination cost — favorable to tenant.', section: 'Section 10.2', tag: 'TERMINATION' },
    { id: 8, type: 'green', title: 'Clear No Subletting Policy', text: 'The no-subletting restriction is clearly stated upfront, avoiding any ambiguity. This is a standard clause in most residential leases.', action: 'Standard clause — no action needed.', section: 'Section 6.1', tag: 'SUBLETTING' },
    { id: 9, type: 'green', title: 'No Pets Policy Clearly Stated', text: 'The no-pets policy is explicitly defined. Note: service animals and emotional support animals cannot be restricted under federal Fair Housing Act.', action: 'Complies with standard lease terms (service animals still protected by FHA).', section: 'Section 5.3', tag: 'PET POLICY' },
  ];